apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-row
  namespace: training-antoine
  labels:
    app: training-row
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training-row
  template:
    metadata:
      labels:
        app: training-row
    spec:
      containers:
      - name: training-row
        image: gcr.io/snyk-technical-services/training-row:dev
        ports:
        - name: training-row
          containerPort: 3000
          protocol: "TCP"